function meta = X3PMetaInfo()
    meta = struct('Creator','','Date','', ...
        'Instrument_Manufacturer', 'Cadre Research Labs', ...
        'Instrument_Model','X3P Toolbox', ...
        'Instrument_Serial','H271106000', ...
        'Instrument_Version','OpenGPS Export V1.0', ...
        'CalibrationDate','2014-04-01T00:00:00.0', ...
        'ProbingSystem_Type','Software', ...
        'ProbingSystem_Identification','X3P Toolbox', ...
        'Comment','No comment');
end